name: compile-and-test
on: [ push ]
jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
    - run: make
    - run: LD_LIBRARY_PATH=. ./main_matrix
    - run: ./main_matrix_static
    - run: make test